#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 21 16:18:07 2020

@author: simon

Code to copy the excel files to every students
"""

import os
import openpyxl as xl
import xlsxwriter as xlw


# Put the full path to the correction file
baseDirectory = "/Users/simon/Desktop/Correction Simon /"

# File with the correction material
os.chdir(baseDirectory + "1 - BIO2043-FinalMaison-Corrige")

# Find the excel file
correctionName = "_corrige_express"

sourceFile = xl.load_workbook("Final_E20_corrige-express.xlsx")
sourceWorkBook = sourceFile.worksheets[0]

nRow = sourceWorkBook.max_row
nCol = sourceWorkBook.max_column

os.chdir(baseDirectory)
for filename in os.listdir():
    os.chdir(baseDirectory)
    if filename ==  "1 - BIO2043-FinalMaison-Corrige" or filename == ".DS_Store":
        pass
    else:
        studentName = filename.split("_")[0]
        os.chdir(baseDirectory + filename)
        allFiles = os.listdir()
        newFileName = studentName + correctionName + ".xlsx"
        if newFileName in allFiles:
            print("File already exist! Skipping...")
            
        else :
            # Create an empty excel file
            newFile = xlw.Workbook(newFileName)
            newFile.close()
            
            # Open the newly created excel file to copy the source file
            newFile = xl.load_workbook(newFileName)
            print(f"Adding new file : {newFileName}")
            newWorksheet = newFile.active
            
            # Loop through every active cells of the excel to copy in the new one
            for col in range(1, nCol+1):
                for row in range(1, nRow+1):
                    data = sourceWorkBook.cell(row = row, column=col)
                    if data.value:
                        #print(data.value)
                        pass
                    newWorksheet.cell(row = row, column=col).value = data.value
              
             
            #if input("Save the file? (y/n)  ") == "y":
            newFile.save(newFileName)
            #else:
                #break
print("done")
                
                